---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  licence: SIL
#  licence_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
 
################################################################################
#


meta:
  author: Dave Gandy
  homepage: http://fortawesome.github.com/Font-Awesome/
  email: dave@davegandy.com
  twitter: http://twitter.com/fortaweso_me/
  github: https://github.com/FortAwesome/Font-Awesome
  licence: CC BY 3.0
  licence_url: http://creativecommons.org/licenses/by/3.0/

  css_prefix: "icon-"
  columns: 4

transform:
  baseline: 0.5
  rescale: 1.052631579
  offset: -0.05


font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: fontawesome

  fullname: Font Awesome
  familyname: Font Awesome

  copyright: Copyright (C) 2012 by Dave Gandy

  ascent: 800
  descent: 200
  weight: "Regular"


glyphs:

  - css: glass
    code: 0xf000
    search: [glass]

  - css: music
    code: 0x1f3b5
    from: 0xf001
    search: [music, note, song, sound]

  - css: search
    code: 0x1f50d
    from: 0xf002
    search: [search, find]

  - css: mail
    code: 0x2709
    from: 0xf003
    search: [mail, email]


  - css: heart
    code: 0x2665
    from: 0xf004
    search: [heart]

  - css: heart-empty
    code: 0x2661
    from: 0xf08a
    search: [heart]


  - css: star
    code: 0x2605
    from: 0xf005
    search: [star]

  - css: star-empty
    code: 0x2606
    from: 0xf006
    search: [star]

  - css: star-half
    code: 0xf089
    search: [star]


  - css: user
    code: 0x1f464
    from: 0xf007
    search: [profile, contact, user]


  - css: video
    code: 0x1f3ac
    from: 0xf008
    search: [movie, video, film]

  - css: videocam
    code: 0x1f3a5
    from: 0xf03d
    search: [facetime, movie, video, film]

  - css: camera
    code: 0x1f4f7
    from: 0xf030
    search: [camera, photo]

  - css: camera-alt
    code: 0xf083
    search: [camera, photo]

  - css: picture
    code: 0x1f304
    from: 0xf03e
    search: [image, picture, photo]


  - css: th-large
    code: 0xf009
    search: [image, list, thumbnails]

  - css: th
    code: 0x268f
    from: 0xf00a
    search: [image, list, thumbnails]

  - css: list
    code: 0x2630
    from: 0xf00b
    search: [list]


  - css: ok
    code: 0x2713
    from: 0xf00c
    search: [ok, yes, check, mark]

  - css: ok-circle
    code: 0xf058
    search: [ok, yes, check, mark]

  - css: ok-circle2
    code: 0xf05d
    search: [ok, yes, check, mark]

  - css: cancel
    code: 0x2715
    from: 0xf00d
    search: [close, cancel, reject]

  - css: cancel-circle
    code: 0x2716
    from: 0xf057
    search: [close, cancel, reject]

  - css: cancel-circle2
    code: 0xf05c
    search: [close, cancel, reject]

  - css: plus
    code: 0x2795
    from: 0xf067
    search: [plus]

  - css: plus-circle
    code: 0xf055
    search: [plus]

  - css: minus
    code: 0x2796
    from: 0xf068
    search: [minus]

  - css: minus-circle
    code: 0xf056
    search: [minus]

  - css: help-circle
    code: 0xf059
    search: [help, question]

  - css: info-circle
    code: 0xf05a
    search: [info]


  - css: home
    code: 0x2302
    from: 0xf015
    search: [home]

  - css: link
    code: 0x1f517
    from: 0xf08e
    search: [link, url]

  - css: lock
    code: 0x1f512
    from: 0xf023
    search: [lock]

  - css: pin
    code: 0x1f4cc
    from: 0xf08d
    search: [pin, pushpin]

  - css: eye
    code: 0xf06e
    search: [eye, subscribe]

  - css: eye-off
    code: 0xf070
    search: [eye, unsubscribe]

  - css: tag
    code: 0xf02b
    search: [tag, category, price, offer]

  - css: tags
    code: 0xf02c
    search: [tag, category, price, offer]

  - css: bookmark
    code: 0x1f516
    from: 0xf02e
    search: [bookmark]

  - css: flag
    code: 0x2691
    from: 0xf024
    search: [flag]

  - css: thumbs-up
    code: 0x1f44d
    from: 0xf087
    search: [thumbs, up, like, vote]
  - css: thumbs-down
    code: 0x1f44e
    from: 0xf088
    search: [thumbs, down, unlike, vote]


  - css: download
    code: 0x1f4e5
    from: 0xf019
    search: [download]
  - css: upload
    code: 0x1f4e4
    from: 0xf093
    search: [upload]


  - css: forward
    code: 0x27a6
    from: 0xf064
    search: [forward]

  - css: export
    code: 0xf045
    search: [export, share]

  - css: pencil
    code: 0x2703
    from: 0xf040
    search: [pencil, write, reply, edit]

  - css: edit
    code: 0xf044
    search: [pencil, write, reply, edit]

  - css: print
    code: 0xf02f
    search: [print]

  - css: retweet
    code: 0xf079
    search: [retweet, twitter]

  - css: comment
    code: 0xf075
    search: [comment, reply, write]

  - css: chat
    code: 0xf086
    search: [chat, talk]


  - css: attention
    code: 0x26a0
    from: 0xf071
    search: [warning]
  - css: attention-circle
    code: 0xf06a


  - css: location
    code: 0xf041
    search: [location, mark, marker]


  - css: trash
    code: 0xf014
    search: [trash, delete]


  - css: doc
    code: 0xf016
    search: [doc, article]

  - css: folder
    code: 0x1f4c1
    from: 0xf07b
    search: [folder]

  - css: folder-open
    code: 0x1f4c2
    from: 0xf07c
    search: [folder]


  - css: cog
    code: 0x2699
    from: 0xf013
    search: [settings, cog, gear]
  - css: cog-alt
    code: 0x26ef
    from: 0xf085
    search: [settings, cog, gear]


  - css: basket
    code: 0xf07a
    search: [basket, shopping, cart]

  - css: calendar
    code: 0x1f4c5
    from: 0xf073
    search: [calendar, date]


  - css: login
    code: 0xf090
    search: [login, signin, enter]
  - css: logout
    code: 0xf08b
    search: [logout, signout, exit]


    # Sound
  - css: volume-off
    code: 0x1f507
    from: 0xf026
    search: [volume, sound, mute]

  - css: volume-down
    code: 0x1f509
    from: 0xf027
    search: [volume, sound]

  - css: volume-up
    code: 0x1f50a
    from: 0xf028
    search: [volume, sound]

  - css: headphones
    code: 0x1f3a7
    from: 0xf025
    search: [sound, music, headphones]


  - css: clock
    code: 0x1f554
    from: 0xf017
    search: [clock, time]


  - css: block
    code: 0x1f6ab
    from: 0xf05e
    search: [block, deny]


  - css: resize-full
    code: 0xf065
    search: [resize, fullscreen]
  - css: resize-small
    code: 0xf066
    search: [resize]
  - css: resize-vertical
    code: 0x2b0c
    from: 0xf07d
    search: [resize]
  - css: resize-horizontal
    code: 0x2b0d
    from: 0xf07e
    search: [resize]

  - css: move
    code: 0xf047
    search: [move]

  - css: zoom-in
    code: 0xf00e
    search: [zoom. scale, in]
  - css: zoom-out
    code: 0xf010
    search: [zoom. scale, out]


    # Arrows
  - css: down-circle2
    code: 0xf01a
    search: [arrow, down, download]
  - css: up-circle2
    code: 0xf01b
    search: [arrow, up, upload]


    # Arrows
  - css: down-open
    code: 0xf078
    search: [arrow, down]
  - css: left-open
    code: 0xf053
    search: [arrow, left]
  - css: right-open
    code: 0xf054
    search: [arrow, right]
  - css: up-open
    code: 0xf077
    search: [arrow, up]


    # Arrows
  - css: down
    code: 0x2193
    from: 0xf063
    search: [arrow, down]
  - css: left
    code: 0x2190
    from: 0xf060
    search: [arrow, left]
  - css: right
    code: 0x2192
    from: 0xf061
    search: [arrow, right]
  - css: up
    code: 0x2191
    from: 0xf062
    search: [arrow, up]


    # Arrows
  - css: cw
    code: 0x27f3
    from: 0xf01e
    search: [reload, redo, repeat]

  - css: arrows-cw
    code: 0xf021
    search: [reload, refresh, update]

  - css: shuffle
    code: 0x1f500
    from: 0xf074
    search: [shuffle]


    # Player
  - css: play
    code: 0x25b6
    from: 0xf04b
    search: [play, player]
  - css: play-circle2
    code: 0xf01d
    search: [play, player]
  - css: stop
    code: 0x25aa
    from: 0xf04d
    search: [stop, player]
  - css: pause
    code: 0x2389
    from: 0xf04c
    search: [pause, player]
  - css: to-end
    code: 0x23ed
    from: 0xf051
    search: [right, player]
  - css: to-end-alt
    code: 0xf050
    search: [right, player]
  - css: to-start
    code: 0x23ee
    from: 0xf048
    search: [left, player]
  - css: to-start-alt
    code: 0xf049
    search: [left, player]
  - css: fast-fw
    code: 0x23e9
    from: 0xf04e
    search: [right, player]
  - css: fast-bw
    code: 0x23ea
    from: 0xf04a
    search: [left, player]
  - css: eject
    code: 0xf052
    search: [eject, player]



  - css: target
    code: 0x1f3af
    from: 0xf05b
    search: [target]

  - css: signal
    code: 0xf012
    search: [broadcast, wifi, signal]

  - css: award
    code: 0x1f3c9
    from: 0xf091
    search: [top, trophy, prize, award]


  - css: inbox
    code: 0xf01c
    search: [inbox]

  - css: flight
    code: 0x2708
    from: 0xf072
    search: [flight, plane, airplane]

  - css: leaf
    code: 0x1f342
    from: 0xf06c
    search: [leaf]


  # Editor
  - css: font
    code: 0xf031
    search: [editor, font]

  - css: bold
    code: 0xf032
    search: [editor, bold]

  - css: italic
    code: 0xf033
    search: [editor, italic]

  - css: text-height
    code: 0xf034
    search: [editor, height]

  - css: text-width
    code: 0xf035
    search: [editor, width]

  - css: align-left
    code: 0xf036
    search: [editor, align, left]

  - css: align-center
    code: 0xf037
    search: [editor, align, center]

  - css: align-right
    code: 0xf038
    search: [editor, align, right]

  - css: align-justify
    code: 0xf039
    search: [editor, align, justify]

  - css: list
    code: 0xf03a
    search: [editor, list]

  - css: indent-left
    code: 0xf03b
    search: [editor, indent]

  - css: indent-right
    code: 0xf03c
    search: [editor, indent]


  # Assorted
  - css: "off"
    code: 0xf011
    search: ["off"]

  - css: road
    code: 0xf018
    search: [road]

  - css: list-alt
    code: 0xf022
    search: [list]

  - css: qrcode
    code: 0xf029
    search: [qrcode]

  - css: barcode
    code: 0xf02a
    search: [barcode]

  - css: book
    code: 0x1f4d5
    from: 0xf02d
    search: [book]

  - css: ajust
    code: 0xf042
    search: [ajust]

  - css: tint
    code: 0xf043
    search: [tint]

  - css: check
    code: 0x2611
    from: 0xf046
    search: [check]

  - css: asterisk
    code: 0x2731
    from: 0xf069
    search: [asterisk]

  - css: gift
    code: 0x1f381
    from: 0xf06b
    search: [gift, present, package, box]

  - css: fire
    code: 0x1f525
    from: 0xf06d
    search: [fire]

  - css: magnet
    code: 0xf076
    search: [magnet]

  - css: chart-bar
    code: 0x1f4ca
    from: 0xf080
    search: [chart, bar, diagram]

  - css: key
    code: 0x1f511
    from: 0xf084
    search: [key]


  # Logos
  - css: github
    code: 0xf092
  - css: twitter
    code: 0xf081
    search: [twitter]
  - css: facebook
    code: 0xf082
    search: [facebook]
  - css: linkedin
    code: 0xf08c


  - css: lemon
    code: 0x1f34b
    from: 0xf094
