---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# demo:
#   css_prefix: "icon-"           # prefix for css-generated classes
#   columns: 4                    # used for html demo page generation
#
# font:                           # all vars from here will be used as font
#                                 # params in fontforge
#                                 # http://fontforge.sourceforge.net/python.html
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Medium
#
#
#
# # Optional. You can apply global resize + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale. Default value calculated
#                                 # from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Symbol code 0x - hex, original
#     code: 0xNNN                 # Symbol code 0x - hex, remapped
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#
#     transform:                  # personal glyph transformation.
#       rescale_rel: 0.9          # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
################################################################################
#
# Mapping rules:
#
# 1. Downshift 1Fxxx -> Fxxx, because 1Fxxx codes not shown in Chrome/Opera
#


demo:
  css_prefix: "icon-"
  columns: 4

transform:
  # baseline: 0.5
  # rescale: 1.0
  offset: -0.05

font:
  version: "1.0"

  # use !!!small!!! letters a-z, or Opera will fail under OS X
  # fontname will be also used as file name.
  fontname: "fontawesome"

  fullname: "Font Awesome"
  familyname: "Font Awesome"

  copyright: "None"

  ascent: 1638
  descent: 410
  weight: "Regular"


glyphs:

  - file: glyph1
    code: 0xf000

  - file: glyph2
    code: 0xf001

  - file: glyph3
    code: 0xf002

  - file: glyph4
    code: 0xf003

  - file: glyph5
    code: 0xf004

  - file: glyph6
    code: 0xf005

  - file: glyph7
    code: 0xf006

  - file: glyph8
    code: 0xf007

  - file: glyph9
    code: 0xf008

  - file: glyph10
    code: 0xf009

  - file: glyph11
    code: 0xf00a

  - file: glyph12
    code: 0xf00b

  - file: glyph13
    code: 0xf00c

  - file: glyph14
    code: 0xf00d

  - file: glyph15
    code: 0xf00e

  - file: glyph16
    code: 0xf010

  - file: glyph17
    code: 0xf011

  - file: glyph18
    code: 0xf012

  - file: glyph19
    code: 0xf013

  - file: glyph20
    code: 0xf014

  - file: glyph21
    code: 0xf015

  - file: glyph22
    code: 0xf016

  - file: glyph23
    code: 0xf017

  - file: glyph24
    code: 0xf018

  - file: glyph25
    code: 0xf019

  - file: glyph26
    code: 0xf01a

  - file: glyph27
    code: 0xf01b

  - file: glyph28
    code: 0xf01c

  - file: glyph29
    code: 0xf01d

  - file: glyph30
    code: 0xf01e

  - file: glyph31
    code: 0xf021

  - file: glyph32
    code: 0xf022

  - file: glyph33
    code: 0xf023

  - file: glyph34
    code: 0xf024

  - file: glyph35
    code: 0xf025

  - file: glyph36
    code: 0xf026

  - file: glyph37
    code: 0xf027

  - file: glyph38
    code: 0xf028

  - file: glyph39
    code: 0xf029

  - file: glyph40
    code: 0xf02a

  - file: glyph41
    code: 0xf02b

  - file: glyph42
    code: 0xf02c

  - file: glyph43
    code: 0xf02d

  - file: glyph44
    code: 0xf02e

  - file: glyph45
    code: 0xf02f

  - file: glyph46
    code: 0xf030

  - file: glyph47
    code: 0xf031

  - file: glyph48
    code: 0xf032

  - file: glyph49
    code: 0xf033

  - file: glyph50
    code: 0xf034

  - file: glyph51
    code: 0xf035

  - file: glyph52
    code: 0xf036

  - file: glyph53
    code: 0xf037

  - file: glyph54
    code: 0xf038

  - file: glyph55
    code: 0xf039

  - file: glyph56
    code: 0xf03a

  - file: glyph57
    code: 0xf03b

  - file: glyph58
    code: 0xf03c

  - file: glyph59
    code: 0xf03d

  - file: glyph60
    code: 0xf03e

  - file: glyph61
    code: 0xf040

  - file: glyph62
    code: 0xf041

  - file: glyph63
    code: 0xf042

  - file: glyph64
    code: 0xf043

  - file: glyph65
    code: 0xf044

  - file: glyph66
    code: 0xf045

  - file: glyph67
    code: 0xf046

  - file: glyph68
    code: 0xf047

  - file: glyph69
    code: 0xf048

  - file: glyph70
    code: 0xf049

  - file: glyph71
    code: 0xf04a

  - file: glyph72
    code: 0xf04b

  - file: glyph73
    code: 0xf04c

  - file: glyph74
    code: 0xf04d

  - file: glyph75
    code: 0xf04e

  - file: glyph76
    code: 0xf050

  - file: glyph77
    code: 0xf051

  - file: glyph78
    code: 0xf052

  - file: glyph79
    code: 0xf053

  - file: glyph80
    code: 0xf054

  - file: glyph81
    code: 0xf055

  - file: glyph82
    code: 0xf056

  - file: glyph83
    code: 0xf057

  - file: glyph84
    code: 0xf058

  - file: glyph85
    code: 0xf059

  - file: glyph86
    code: 0xf05a

  - file: glyph87
    code: 0xf05b

  - file: glyph88
    code: 0xf05c

  - file: glyph89
    code: 0xf05d

  - file: glyph90
    code: 0xf05e

  - file: glyph91
    code: 0xf060

  - file: glyph92
    code: 0xf061

  - file: glyph93
    code: 0xf062

  - file: glyph94
    code: 0xf063

  - file: glyph95
    code: 0xf064

  - file: glyph96
    code: 0xf065

  - file: glyph97
    code: 0xf066

  - file: glyph98
    code: 0xf067

  - file: glyph99
    code: 0xf068

  - file: glyph100
    code: 0xf069

  - file: glyph101
    code: 0xf06a

  - file: glyph102
    code: 0xf06b

  - file: glyph103
    code: 0xf06c

  - file: glyph104
    code: 0xf06d

  - file: glyph105
    code: 0xf06e

  - file: glyph106
    code: 0xf070

  - file: glyph107
    code: 0xf071

  - file: glyph108
    code: 0xf072

  - file: glyph109
    code: 0xf073

  - file: glyph110
    code: 0xf074

  - file: glyph111
    code: 0xf075

  - file: glyph112
    code: 0xf076

  - file: glyph113
    code: 0xf077

  - file: glyph114
    code: 0xf078

  - file: glyph115
    code: 0xf079

  - file: glyph116
    code: 0xf07a

  - file: glyph117
    code: 0xf07b

  - file: glyph118
    code: 0xf07c

  - file: glyph119
    code: 0xf07d

  - file: glyph120
    code: 0xf07e

  - file: glyph121
    code: 0xf080

  - file: glyph122
    code: 0xf081

  - file: glyph123
    code: 0xf082

  - file: glyph124
    code: 0xf083

  - file: glyph125
    code: 0xf084

  - file: glyph126
    code: 0xf085

  - file: glyph127
    code: 0xf086

  - file: glyph128
    code: 0xf087

  - file: glyph129
    code: 0xf088

  - file: glyph130
    code: 0xf089

  - file: glyph131
    code: 0xf08a

  - file: glyph132
    code: 0xf08b

  - file: glyph133
    code: 0xf08c

  - file: glyph134
    code: 0xf08d

  - file: glyph135
    code: 0xf08e

  - file: glyph136
    code: 0xf090

  - file: glyph137
    code: 0xf091

  - file: glyph138
    code: 0xf092

  - file: glyph139
    code: 0xf093

  - file: glyph140
    code: 0xf094
